isomerpages/moe-damaisec

- _information/Direct School Admission (DSA).md
> Pull request 3 May 2023

- _information/Students/Assessment Matters.md
Fix broken link in schedule of assessment
> Pull Request 28 Jun

- _information/Parents/Holiday Schedule.md
> Pull request 30/8

- _information/Parents/Holiday Schedule.md
> Pull request 30 Oct

- _our-curriculum/Co Curricular Activities (CCA)/Girl Guides.md
> girl guide - photos not showing 

- _our-people/School Management Committee.md
> amend typo on SMC page

- _our-people/Departments/Science Department.md
> updated dept page

- _information/Students/Assessment Matters.md
- _information/Students/Safety Matters.md
Amended and updated some additional texts on assessments and safety page
> amended typo

- _information/Students/Safety Matters.md
removed safety for bicycle infographics at Mr Ng's request
> removed safety for bicycle infographics at Mr Ng's request

- _information/Students/Assessment Matters.md
> remove of 2023 exam 

- _information/Parents/Device Management Application.md
> dma page edit

- _our-people/Form Teachers/Sec 1 Form Teachers.md
- _our-people/Form Teachers/Sec 2 Form Teachers.md
> update of teachers email

- _information/Parents/Holiday Schedule.md
update of march 2024 holidays schedule
> update of march holidays review

- _our-people/Exec & Admin Staff (EAS).md
removal of Mr Toh from EAS list
> removal of Mr Toh from EAS list

- _our-people/Exec & Admin Staff (EAS).md
updated OM details on EAS page (email and name changed from Mr Chew to Mr Ang)
> updated OM details on EAS page

- _information/Parents/Device Management Application.md
changed end of week to end of month
> update of DMA page

- _information/Teachers.md
updated ICT request form
removed ICON link as it's accessed via MIMS now
> updated teachers' useful links

- _information/Students/Assessment Matters.md
- pages/Announcements.md
updated announcement and assessment matters
> announcement

- _information/Parents/Holiday Schedule.md
information> holiday schedule for june 2024
> update of school holiday program

- _our-people/Counselling and Learning Support.md
- _our-people/Departments/Craft & Technology Department.md
- _our-people/Departments/English Language & Literature Department.md
- _our-people/Departments/Humanities Department.md
- _our-people/Departments/Mathematics Department.md
- _our-people/Departments/Mother Tongue Languages Department.md
- _our-people/Form Teachers/Sec 1 Form Teachers.md
- _our-people/Form Teachers/Sec 2 Form Teachers.md
- _our-people/Form Teachers/Sec 3 Form Teachers.md
- _our-people/Form Teachers/Sec 4&5 Form Teachers.md
> change of staff

- _our-people/Counselling and Learning Support.md
> amend name

- _information/Parents/Holiday Schedule.md
updated holidays schedule for september
> updated holidays schedule

- _information/Students/ICT Matters.md
> update on ict matters

- _information/Canteen Advertisement.md
new canteen advertisement for japanese/korean stall
> canteen advertisement

- _information/Parents/Holiday Schedule.md
> updated holiday schedule

- _information/Canteen Advertisement.md
extended canteen advertisement dates
> extended canteen advertisement

- _our-curriculum/Character and Citizenship Education.md
removed broken link from CCE page
> removed broken link

- _information/Canteen Advertisement.md
- _our-community/Alumni.md
updated: canteen advertisement and alumni page
> updated: canteen advertisement and alumni page

- _our-community/Alumni.md
changed alumni form from 5 to 10 minutes
> changed alumni form from 5 to 10 minutes

- index.md
> request n level

- _data/navigation.yml
- index.md
remove announcement, update calendar
> remove announcement, update calendar

- _information/Canteen Advertisement.md
- _our-people/Departments/Craft & Technology Department.md
- _our-people/Departments/Humanities Department.md
- _our-people/Departments/Mathematics Department.md
- _our-people/Departments/Mother Tongue Languages Department.md
- _our-people/Departments/Science Department.md
updated staff list, canteen ad
> updated staff list, canteen ad

- _information/Students/Release of GCE O Level Examination Results 2023.md
- _information/Students/Release of GCE O Level Examination Results 2024.md
- _information/collection.yml
- index.md
- pages/Announcements.md
> update o level page

- _information/Parents/Cyber Wellness Tips.md
updated broken link on cyber wellness
> update csa link

- _information/Parents/Holiday Schedule.md
updated march holiday schedule
> updated march holiday schedule

- _information/Canteen Advertisement.md
> Canteen advertisement update
